### ISSUE TITLE
[Project] Implement CLI control wechaty

### ISSUE THREAD

**Issue by kis87988** [wechaty/summer#55]
Hello students!

Web GUI is great, but not great enough if we just want to have a terminal while we are doing the implementation testing, If we can have a CLI tool to control the bot and CLI likely GUI to have a display dashboard to relate control(like tmux). That will be great. 
I believe there is a more open ideas we can integrate. I think this would be a good project for summer

Link to #30

Required skills for all projects
- git version control
- collaborative software development on github.com
- software development in at least one of Wechaty's six languages on at least one of Linux, macOS, and Windows.

Required skills: TypeScript programming language, Python, CLI, Linux.

Useful Links
https://github.com/wechaty/wechaty

**Comment by huan** [comment]
Merge to #80

@kis87988 Please feel free to join us at any time!
